steps:
  - name: 'golang:latest'
    args: ['go', 'test', '-v', './src/...']

  - name: 'golang:latest'
    args: ['go', 'vet', './src/...']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash'
    args:
      [
        '-c',
        'gcloud secrets versions access latest --secret=backend-secrets > secrets.yaml',
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

options:
  env:
    - 'CGO_ENABLED=0'
